name: Build and deploy website

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v1

      - name: Setup NodeJS environement
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      
      - name: Load cached dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
                
      - name: Install dependencies
        run: yarn install

      - name: Build Website
        run: yarn build
      
      - name: Deploy Website
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}